#!/usr/bin/python
__author__ = "Bassim Aly"
__EMAIL__ = "basim.alyy@gmail.com"

from napalm import get_network_driver
from prettytable import PrettyTable
import argparse

Interface_Errors = PrettyTable(['Interface', 'RX Errors', 'Tx Errors', "mac"])
Interface_Errors.padding_width = 1

Interface_Discards = PrettyTable(['Interface', 'RX Discards', 'Tx Discards', "mac"])
Interface_Discards.padding_width = 1

parser = argparse.ArgumentParser()
parser.add_argument("-i", "--mx_ip", help="Enter the ip address")
args = parser.parse_args()
device_ip = args.mx_ip

junos_driver = get_network_driver("junos")
mx_router = junos_driver(username="root",
                         password="access123",
                         hostname=device_ip)
mx_router.open()
if mx_router.is_alive()["is_alive"]:
    print "working on device {}".format(device_ip)
    interfaces_counters = mx_router.get_interfaces_counters()
    interfaces = mx_router.get_interfaces()
    for intf, intf_data in interfaces_counters.iteritems():
        Interface_Errors.add_row([intf, intf_data["rx_errors"], intf_data["tx_errors"],interfaces[intf]["mac_address"]])
        Interface_Discards.add_row([intf, intf_data["rx_discards"], intf_data["tx_discards"],interfaces[intf]["mac_address"]])

        if  intf_data["rx_errors"] > 0 or \
            intf_data["tx_errors"] > 0 or \
            intf_data["rx_discards"] > 0 or \
            intf_data["tx_discards"] > 0:
            print "interface {} has an error, please check" .format(intf)

print Interface_Errors
print "=" * 50
print Interface_Discards

data = {'em0': {'rx_broadcast_packets': -1,
                'rx_discards': 0,
                'rx_errors': 0,
                'rx_multicast_packets': -1,
                'rx_octets': 0,
                'rx_unicast_packets': -1,
                'tx_broadcast_packets': -1,
                'tx_discards': 0,
                'tx_errors': 0,
                'tx_multicast_packets': -1,
                'tx_octets': 0,
                'tx_unicast_packets': -1},
        'em1': {'rx_broadcast_packets': -1,
                'rx_discards': 0,
                'rx_errors': 0,
                'rx_multicast_packets': -1,
                'rx_octets': 0,
                'rx_unicast_packets': -1,
                'tx_broadcast_packets': -1,
                'tx_discards': 0,
                'tx_errors': 0,
                'tx_multicast_packets': -1,
                'tx_octets': 0,
                'tx_unicast_packets': -1},
        'em2': {'rx_broadcast_packets': -1,
                'rx_discards': 0,
                'rx_errors': 0,
                'rx_multicast_packets': -1,
                'rx_octets': 0,
                'rx_unicast_packets': -1,
                'tx_broadcast_packets': -1,
                'tx_discards': 0,
                'tx_errors': 0,
                'tx_multicast_packets': -1,
                'tx_octets': 0,
                'tx_unicast_packets': -1},
        'em3': {'rx_broadcast_packets': -1,
                'rx_discards': 0,
                'rx_errors': 0,
                'rx_multicast_packets': -1,
                'rx_octets': 0,
                'rx_unicast_packets': -1,
                'tx_broadcast_packets': -1,
                'tx_discards': 0,
                'tx_errors': 0,
                'tx_multicast_packets': -1,
                'tx_octets': 0,
                'tx_unicast_packets': -1},
        'em4': {'rx_broadcast_packets': -1,
                'rx_discards': 0,
                'rx_errors': 0,
                'rx_multicast_packets': -1,
                'rx_octets': 0,
                'rx_unicast_packets': -1,
                'tx_broadcast_packets': -1,
                'tx_discards': 0,
                'tx_errors': 0,
                'tx_multicast_packets': -1,
                'tx_octets': 0,
                'tx_unicast_packets': -1},
        'em5': {'rx_broadcast_packets': -1,
                'rx_discards': 0,
                'rx_errors': 0,
                'rx_multicast_packets': -1,
                'rx_octets': 0,
                'rx_unicast_packets': -1,
                'tx_broadcast_packets': -1,
                'tx_discards': 0,
                'tx_errors': 0,
                'tx_multicast_packets': -1,
                'tx_octets': 0,
                'tx_unicast_packets': -1},
        'em6': {'rx_broadcast_packets': -1,
                'rx_discards': 0,
                'rx_errors': 0,
                'rx_multicast_packets': -1,
                'rx_octets': 0,
                'rx_unicast_packets': -1,
                'tx_broadcast_packets': -1,
                'tx_discards': 0,
                'tx_errors': 0,
                'tx_multicast_packets': -1,
                'tx_octets': 0,
                'tx_unicast_packets': -1},
        'em7': {'rx_broadcast_packets': -1,
                'rx_discards': 0,
                'rx_errors': 0,
                'rx_multicast_packets': -1,
                'rx_octets': 0,
                'rx_unicast_packets': -1,
                'tx_broadcast_packets': -1,
                'tx_discards': 0,
                'tx_errors': 0,
                'tx_multicast_packets': -1,
                'tx_octets': 0,
                'tx_unicast_packets': -1},
        'ge-0/0/0': {'rx_broadcast_packets': 0,
                     'rx_discards': 0,
                     'rx_errors': 0,
                     'rx_multicast_packets': 0,
                     'rx_octets': 2215300,
                     'rx_unicast_packets': 0,
                     'tx_broadcast_packets': 0,
                     'tx_discards': 0,
                     'tx_errors': 0,
                     'tx_multicast_packets': 0,
                     'tx_octets': 586788,
                     'tx_unicast_packets': 0},
        'ge-0/0/1': {'rx_broadcast_packets': 0,
                     'rx_discards': 0,
                     'rx_errors': 0,
                     'rx_multicast_packets': 0,
                     'rx_octets': 0,
                     'rx_unicast_packets': 0,
                     'tx_broadcast_packets': 0,
                     'tx_discards': 0,
                     'tx_errors': 0,
                     'tx_multicast_packets': 0,
                     'tx_octets': 0,
                     'tx_unicast_packets': 0},
        'ge-0/0/2': {'rx_broadcast_packets': 0,
                     'rx_discards': 0,
                     'rx_errors': 0,
                     'rx_multicast_packets': 0,
                     'rx_octets': 0,
                     'rx_unicast_packets': 0,
                     'tx_broadcast_packets': 0,
                     'tx_discards': 0,
                     'tx_errors': 0,
                     'tx_multicast_packets': 0,
                     'tx_octets': 0,
                     'tx_unicast_packets': 0},
        'ge-0/0/3': {'rx_broadcast_packets': 0,
                     'rx_discards': 0,
                     'rx_errors': 0,
                     'rx_multicast_packets': 0,
                     'rx_octets': 0,
                     'rx_unicast_packets': 0,
                     'tx_broadcast_packets': 0,
                     'tx_discards': 0,
                     'tx_errors': 0,
                     'tx_multicast_packets': 0,
                     'tx_octets': 0,
                     'tx_unicast_packets': 0},
        'ge-0/0/4': {'rx_broadcast_packets': 0,
                     'rx_discards': 0,
                     'rx_errors': 0,
                     'rx_multicast_packets': 0,
                     'rx_octets': 0,
                     'rx_unicast_packets': 0,
                     'tx_broadcast_packets': 0,
                     'tx_discards': 0,
                     'tx_errors': 0,
                     'tx_multicast_packets': 0,
                     'tx_octets': 0,
                     'tx_unicast_packets': 0},
        'ge-0/0/5': {'rx_broadcast_packets': 0,
                     'rx_discards': 0,
                     'rx_errors': 0,
                     'rx_multicast_packets': 0,
                     'rx_octets': 648236,
                     'rx_unicast_packets': 0,
                     'tx_broadcast_packets': 0,
                     'tx_discards': 0,
                     'tx_errors': 0,
                     'tx_multicast_packets': 0,
                     'tx_octets': 2526535,
                     'tx_unicast_packets': 0},
        'ge-0/0/6': {'rx_broadcast_packets': 0,
                     'rx_discards': 0,
                     'rx_errors': 0,
                     'rx_multicast_packets': 0,
                     'rx_octets': 0,
                     'rx_unicast_packets': 0,
                     'tx_broadcast_packets': 0,
                     'tx_discards': 0,
                     'tx_errors': 0,
                     'tx_multicast_packets': 0,
                     'tx_octets': 0,
                     'tx_unicast_packets': 0},
        'ge-0/0/7': {'rx_broadcast_packets': 0,
                     'rx_discards': 0,
                     'rx_errors': 0,
                     'rx_multicast_packets': 0,
                     'rx_octets': 0,
                     'rx_unicast_packets': 0,
                     'tx_broadcast_packets': 0,
                     'tx_discards': 0,
                     'tx_errors': 0,
                     'tx_multicast_packets': 0,
                     'tx_octets': 0,
                     'tx_unicast_packets': 0},
        'ge-0/0/8': {'rx_broadcast_packets': 0,
                     'rx_discards': 0,
                     'rx_errors': 0,
                     'rx_multicast_packets': 0,
                     'rx_octets': 0,
                     'rx_unicast_packets': 0,
                     'tx_broadcast_packets': 0,
                     'tx_discards': 0,
                     'tx_errors': 0,
                     'tx_multicast_packets': 0,
                     'tx_octets': 0,
                     'tx_unicast_packets': 0},
        'ge-0/0/9': {'rx_broadcast_packets': 0,
                     'rx_discards': 0,
                     'rx_errors': 0,
                     'rx_multicast_packets': 0,
                     'rx_octets': 0,
                     'rx_unicast_packets': 0,
                     'tx_broadcast_packets': 0,
                     'tx_discards': 0,
                     'tx_errors': 0,
                     'tx_multicast_packets': 0,
                     'tx_octets': 0,
                     'tx_unicast_packets': 0},
        'mtun': {'rx_broadcast_packets': -1,
                 'rx_discards': -1,
                 'rx_errors': -1,
                 'rx_multicast_packets': -1,
                 'rx_octets': 0,
                 'rx_unicast_packets': -1,
                 'tx_broadcast_packets': -1,
                 'tx_discards': -1,
                 'tx_errors': -1,
                 'tx_multicast_packets': -1,
                 'tx_octets': 0,
                 'tx_unicast_packets': -1},
        'vtep': {'rx_broadcast_packets': -1,
                 'rx_discards': 0,
                 'rx_errors': 0,
                 'rx_multicast_packets': -1,
                 'rx_octets': 0,
                 'rx_unicast_packets': -1,
                 'tx_broadcast_packets': -1,
                 'tx_discards': 0,
                 'tx_errors': 0,
                 'tx_multicast_packets': -1,
                 'tx_octets': 0,
                 'tx_unicast_packets': -1}}
